/*
 * File: app/view/AddExpenseForm.js
 * Date: Sun Oct 23 2011 11:17:57 GMT-0500 (CDT)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.view.AddExpenseForm', {
    extend: 'MyApp.view.ui.AddExpenseForm',
    alias: 'widget.addexpenseform',

    initialize: function() {
        var me = this;
        me.callParent(arguments);
    },

    onCancelTap: function(button, e, options) {
        button.up('formpanel').reset();
        button.up('#mainPanel').setActiveItem(0);
    },

    onSubmitTap: function(button, e, options) {
        var form = button.up('formpanel'),
        mainPanel = form.up('#mainPanel'),
        store = mainPanel.down('#expenseList').getStore(),
        ts = new Date(),
        expenseRecord = form.getValues();
        
        // Add additional data
        expenseRecord.username = MyApp.username;
        expenseRecord.timestamp = ts;
        
        // Send message to the queue - no relation to the store
        Ext.io.send('queue/expense', { 
            'type': 'newexpense',
            'storeid': 'expenseDB',
            'username': expenseRecord.username,
            'merchant': expenseRecord.merchant,
            'category': expenseRecord.category,
            'amount': expenseRecord.amount,
            'timestamp': Ext.Date.format(ts, 'Y-m-d g.i')
        });
        
        //Store to local storage and sync to remote syncstorage
        store.add(expenseRecord);
        store.sync();
        
        //Confirmation
        Ext.Msg.alert(null, "Expense Added Successfully", function() {
            //Back to list
            form.reset();
            mainPanel.setActiveItem(0);
        });
    }

});