/*
 * File: app/view/AddExpenseForm.js
 * Date: Sat Oct 22 2011 23:39:34 GMT-0500 (CDT)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.view.AddExpenseForm', {
    extend: 'MyApp.view.ui.AddExpenseForm',

    initialize: function() {
        var me = this;
        me.callParent(arguments);
    }

});