/*
 * File: app/view/ListPanel.js
 * Date: Sat Oct 22 2011 23:56:22 GMT-0500 (CDT)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.view.ListPanel', {
    extend: 'MyApp.view.ui.ListPanel',
    alias: 'widget.listpanel',

    initialize: function() {
        var me = this;
        me.callParent(arguments);
    }

});