/*
 * File: app/view/LoginForm.js
 * Date: Sun Oct 23 2011 11:17:57 GMT-0500 (CDT)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Ext.define('MyApp.view.LoginForm', {
    extend: 'MyApp.view.ui.LoginForm',
    alias: 'widget.loginform',

    initialize: function() {
        var me = this;
        me.callParent(arguments);
    },

    onLoginTap: function(button, e, options) {
        var top = button.up('topview');
        MyApp.username = button.up('formpanel').getValues().username;
        top.down('#loggedInUserName').setHtml(MyApp.username);
        top.setActiveItem(1);
    }

});