/*
 * File: app/view/ui/AddExpenseForm.js
 * Date: Sun Oct 23 2011 11:17:57 GMT-0500 (CDT)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.AddExpenseForm', {
    extend: 'Ext.form.Panel',

    config: {
        layout: {
            pack: 'center',
            type: 'vbox'
        }
    },

    initialize: function() {
        var me = this;
        me.setItems([
            {
                xtype: 'fieldset',
                title: 'Add New Expense',
                items: [
                    {
                        xtype: 'textfield',
                        name: 'merchant',
                        required: true,
                        label: {
                            width: '35%',
                            text: 'Merchant'
                        }
                    },
                    {
                        xtype: 'numberfield',
                        name: 'amount',
                        required: true,
                        label: {
                            width: '35%',
                            text: 'Amount'
                        }
                    },
                    {
                        xtype: 'selectfield',
                        name: 'category',
                        options: [
                            {
                                text: 'Uncategorized',
                                value: null
                            },
                            {
                                text: 'Lodging',
                                value: 'lodging'
                            },
                            {
                                text: 'Transportation',
                                value: 'transportation'
                            },
                            {
                                text: 'Food/Drink',
                                value: 'food'
                            }
                        ],
                        label: {
                            width: '35%',
                            text: 'Category'
                        }
                    }
                ]
            },
            {
                xtype: 'button',
                ui: 'confirm',
                text: 'Submit',
                listeners: [
                    {
                        event: 'tap',
                        scope: me,
                        fn: me.onSubmitTap
                    }
                ]
            },
            {
                xtype: 'button',
                style: 'margin-top:1em;',
                ui: 'decline',
                text: 'Cancel',
                listeners: [
                    {
                        event: 'tap',
                        scope: me,
                        fn: me.onCancelTap
                    }
                ]
            }
        ]);
        me.callParent(arguments);
    },

    onSubmitTap: function(button, e, options) {
        
    },

    onCancelTap: function(button, e, options) {
        
    }

});