/*
 * File: app/view/ui/ListPanel.js
 * Date: Sat Oct 22 2011 23:48:05 GMT-0500 (CDT)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.ListPanel', {
    extend: 'Ext.Panel',

    config: {
        layout: {
            type: 'fit'
        }
    },

    initialize: function() {
        var me = this;
        me.setItems([
            {
                xtype: 'list',
                itemId: 'expenseList',
                itemTpl: Ext.create('Ext.XTemplate', 
                    '<div class="merchant">{merchant}</div><div class="category">{category}</div><div class="amount">{amount}</div>'
                )
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'button',
                        ui: 'action-round',
                        text: 'Add New Expense',
                        flex: 1
                    }
                ]
            }
        ]);
        me.callParent(arguments);
    }

});