/*
 * File: app/view/ui/ListPanel.js
 * Date: Sun Oct 23 2011 11:17:57 GMT-0500 (CDT)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.ListPanel', {
    extend: 'Ext.Panel',

    config: {
        layout: {
            type: 'fit'
        }
    },

    initialize: function() {
        var me = this;
        me.setItems([
            {
                xtype: 'list',
                itemId: 'expenseList',
                itemTpl: Ext.create('Ext.XTemplate', 
                    '<div class="merchant">{merchant}</div><div class="category">{category}</div><div class="amount">{amount}</div>'
                ),
                listeners: [
                    {
                        event: 'painted',
                        scope: me,
                        fn: me.onListPainted
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'button',
                        ui: 'action-round',
                        text: 'Add New Expense',
                        flex: 1,
                        listeners: [
                            {
                                event: 'tap',
                                scope: me,
                                fn: me.onSwitchToAddTap
                            }
                        ]
                    }
                ]
            }
        ]);
        me.callParent(arguments);
    },

    onListPainted: function(component, options) {
        
    },

    onSwitchToAddTap: function(button, e, options) {
        
    }

});