/*
 * File: app/view/ui/LoginForm.js
 * Date: Sat Oct 22 2011 23:56:22 GMT-0500 (CDT)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.LoginForm', {
    extend: 'Ext.form.Panel',

    config: {
        layout: {
            pack: 'center',
            type: 'vbox'
        }
    },

    initialize: function() {
        var me = this;
        me.setItems([
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'emailfield',
                        name: 'username',
                        label: {
                            width: '35%',
                            text: 'Username'
                        },
                        input: {
                            placeHolder: 'email@example.com'
                        }
                    },
                    {
                        xtype: 'passwordfield',
                        name: 'password',
                        label: {
                            width: '35%',
                            text: 'Password'
                        }
                    }
                ]
            },
            {
                xtype: 'button',
                ui: 'confirm',
                text: 'Log In'
            }
        ]);
        me.callParent(arguments);
    }

});