/*
 * File: app/view/ui/MainPanel.js
 * Date: Sun Oct 23 2011 11:17:57 GMT-0500 (CDT)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.MainPanel', {
    extend: 'Ext.Panel',
    requires: [
        'MyApp.view.ListPanel',
        'MyApp.view.AddExpenseForm'
    ],

    config: {
        layout: {
            animation: 'slide',
            type: 'card'
        }
    },

    initialize: function() {
        var me = this;
        me.setItems([
            {
                xtype: 'toolbar',
                ui: 'light',
                docked: 'top',
                items: [
                    {
                        xtype: 'component',
                        html: '[email@example.com]',
                        itemId: 'loggedInUserName',
                        style: 'color:#FFF; padding:0 .5em; font-size: 0.8em;',
                        flex: 1
                    },
                    {
                        xtype: 'button',
                        text: 'Log Out',
                        listeners: [
                            {
                                event: 'tap',
                                scope: me,
                                fn: me.onLogoutTap
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'listpanel',
                itemId: 'listPanel'
            },
            {
                xtype: 'addexpenseform',
                itemId: 'addExpenseForm'
            }
        ]);
        me.callParent(arguments);
    },

    onLogoutTap: function(button, e, options) {
        
    }

});