/*
 * File: app/view/ui/Viewport.js
 * Date: Sat Oct 22 2011 23:56:22 GMT-0500 (CDT)
 *
 * This file was generated by Sencha Designer version 2.0.0.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ui.Viewport', {
    extend: 'Ext.Panel',
    requires: [
        'MyApp.view.LoginForm',
        'MyApp.view.MainPanel'
    ],

    config: {
        fullscreen: true,
        layout: {
            animation: 'fade',
            type: 'card'
        }
    },

    initialize: function() {
        var me = this;
        me.setItems([
            {
                xtype: 'toolbar',
                title: 'Sencha Expenses',
                docked: 'top'
            },
            {
                xtype: 'loginform',
                itemId: 'loginForm'
            },
            {
                xtype: 'mainpanel',
                itemId: 'mainPanel'
            }
        ]);
        me.callParent(arguments);
    }

});